#!/bin/bash
export SSO_DOCKER_CENTOS_VERSION=${SSO_DOCKER_CENTOS_VERSION:-latest}
export SSO_DOCKER_FROM_IMAGE="centos:$SSO_DOCKER_CENTOS_VERSION"
export SSO_DOCKER_IMAGE="miracl-sso-centos:$SSO_DOCKER_CENTOS_VERSION"
export SSO_DOCKER_NAME=centos
export SSO_DOCKER_PORT_BASE=${SSO_DOCKER_PORT_BASE:-9000}
export SSO_DOCKER_CONTEXT=$(pwd)
export SSO_DOCKER_REDIS=redis

. ../compose/env.sh
