#!/bin/bash
MIRACL_CONTAINER=${MIRACL_CONTAINER:-miracl-sso-ubuntu}
MIRACL_SERVICE=${MIRACL_SERVICE:-srv-idp}
MIRACL_SERVICE_FULL=${MIRACL_SERVICE_FULL:-miracl-$MIRACL_SERVICE}
MIRACL_RUN_OPTS=${MIRACL_RUN_OPTS:-"-p 8000:8000"}
REDIS_SERVICE=redis-server
