version: "2"
services:
  sso:
    container_name: $SSO_DOCKER_SSO_NAME
    image: $SSO_DOCKER_IMAGE
    build:
      context: $SSO_DOCKER_CONTEXT
      args:
        idp_port: $SSO_DOCKER_IDP_PORT_INT
        radius_port: $SSO_DOCKER_RADIUS_PORT_INT
    hostname: idp
    ports:
      - $SSO_DOCKER_IDP_PORT:$SSO_DOCKER_IDP_PORT_INT
      - $SSO_DOCKER_RADIUS_PORT:$SSO_DOCKER_RADIUS_PORT_INT
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup 
    privileged: true
  consul:
    container_name: $SSO_DOCKER_CONSUL_NAME
    image: progrium/consul
    command: -server -bootstrap 
    hostname: consul 
    ports:
      - $SSO_DOCKER_CONSUL_PORT:8500
  statsd:
    container_name: $SSO_DOCKER_STATSD_NAME
    image: hopsoft/graphite-statsd
    hostname: statsd 
    ports:
      - $SSO_DOCKER_STATSD_PORT:80
    expose:
      - 53/udp
      - 2003
      - 2004
      - 2023
      - 2024
      - '8125/udp'
      - 8126
  redis:
    container_name: $SSO_DOCKER_REDIS_NAME
    image: redis 
    hostname: redis 
    ports:
      - $SSO_DOCKER_REDIS_PORT:6379
  ldap:
    container_name: $SSO_DOCKER_LDAP_NAME
    image: osixia/openldap  
    hostname: ldap 
    command: --loglevel debug
    environment:
      LDAP_ORGANISATION:  "TEST"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN:  "ou=admin,dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "password" 
      LDAP_CONFIG_PASSWORD:  "password" 
    ports:
      - $SSO_DOCKER_LDAP_PORT:389
      - 636
  ldapgui:
    container_name: $SSO_DOCKER_LDAPGUI_NAME
    image: osixia/phpldapadmin
    hostname: ldapigui 
    ports:
      - $SSO_DOCKER_LDAPGUI_PORT:443
    depends_on:
      - ldap
    volumes:
      - ./ldap.startup.yml:/container/environment/01-miracl/env.yaml
  syslog:
    container_name: $SSO_DOCKER_SYSLOG_NAME
    build:
      context: ./syslog
    hostname: syslog
    expose:
      - 514/udp
  sp:
    container_name: $SSO_DOCKER_SP_NAME
    build:
      context: ./sp
    hostname: sp
    ports:
      - $SSO_DOCKER_SP_PORT:80
    environment:
      SP_SITEURL: "$SSO_DOCKER_SP_SITEURL"
      SP_ACSURL: "$SSO_DOCKER_SP_ACSURL"
      SP_LOGOUTURL: "$SSO_DOCKER_SP_LOGOUTURL"
      SP_ENTITYID: "$SSO_DOCKER_SP_BASEURL"
      SP_CERT: "$SSO_DOCKER_SP_CERT"
      SP_KEY: "$SSO_DOCKER_SP_KEY"
      IDP_BASEURL: "$SSO_DOCKER_IDP_BASEURL"
      IDP_ENTITYID: "$SSO_DOCKER_IDP_BASEURL"
      IDP_CERT: "$SSO_DOCKER_IDP_CERT"
