version: "2"
services:
  sso:
    container_name: $SSO_DOCKER_SSO_NAME
    image: $SSO_DOCKER_IMAGE
    build:
      context: $SSO_DOCKER_CONTEXT
      args:
        idp_port: $SSO_DOCKER_IDP_PORT_INT
        radius_port: $SSO_DOCKER_RADIUS_PORT_INT
        from_image: $SSO_DOCKER_FROM_IMAGE
    networks:
      - default
      - radius
    ports:
      - $SSO_DOCKER_IDP_PORT:$SSO_DOCKER_IDP_PORT_INT
      - $SSO_DOCKER_RADIUS_PORT:$SSO_DOCKER_RADIUS_PORT_INT/udp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup 
    privileged: true
  consul:
    container_name: $SSO_DOCKER_CONSUL_NAME
    image: progrium/consul
    command: -server -bootstrap 
    ports:
      - $SSO_DOCKER_CONSUL_PORT:8500
  statsd:
    container_name: $SSO_DOCKER_STATSD_NAME
    image: hopsoft/graphite-statsd
    ports:
      - $SSO_DOCKER_STATSD_PORT:80
    expose:
      - 53/udp
      - 2003
      - 2004
      - 2023
      - 2024
      - '8125/udp'
      - 8126
  redis:
    container_name: $SSO_DOCKER_REDIS_NAME
    image: redis 
    ports:
      - $SSO_DOCKER_REDIS_PORT:6379
  ldap:
    container_name: $SSO_DOCKER_LDAP_NAME
    image: osixia/openldap  
    command: --loglevel debug
    environment:
      LDAP_ORGANISATION:  "TEST"
      LDAP_DOMAIN: "example.com"
      LDAP_BASE_DN:  "ou=admin,dc=example,dc=com"
      LDAP_ADMIN_PASSWORD: "password" 
      LDAP_CONFIG_PASSWORD:  "password" 
    ports:
      - $SSO_DOCKER_LDAP_PORT:389
      - 636
  ldapgui:
    container_name: $SSO_DOCKER_LDAPGUI_NAME
    image: osixia/phpldapadmin
    ports:
      - $SSO_DOCKER_LDAPGUI_PORT:443
    depends_on:
      - ldap
    volumes:
      - ./ldap.startup.yml:/container/environment/01-miracl/env.yaml
  syslog:
    container_name: $SSO_DOCKER_SYSLOG_NAME
    build:
      context: ./syslog
    hostname: syslog
    expose:
      - 514/udp
  sp:
    container_name: $SSO_DOCKER_SP_NAME
    build:
      context: ./sp
    ports:
      - $SSO_DOCKER_SP_PORT:80
    environment:
      SP_SITEURL: "$SSO_DOCKER_SP_SITEURL"
      SP_ACSURL: "$SSO_DOCKER_SP_ACSURL"
      SP_LOGOUTURL: "$SSO_DOCKER_SP_LOGOUTURL"
      SP_ENTITYID: "$SSO_DOCKER_SP_BASEURL"
      SP_CERT: "$SSO_DOCKER_SP_CERT"
      SP_KEY: "$SSO_DOCKER_SP_KEY"
      IDP_BASEURL: "$SSO_DOCKER_IDP_BASEURL"
      IDP_ENTITYID: "$SSO_DOCKER_IDP_BASEURL"
      IDP_CERT: "$SSO_DOCKER_IDP_CERT"

  openssh:
    container_name: $SSO_DOCKER_OPENSSH_NAME
    image: miracl/sso_openssh
    ports:
      - $SSO_DOCKER_OPENSSH_PORT_INT:$SSO_DOCKER_OPENSSH_PORT
    networks:
      radius:
        ipv4_address: $SSO_DOCKER_OPENSSH_IP
    environment:
      RADIUS_SERVER_ADDRESS: sso
      RADIUS_SERVER_PORT: "$SSO_DOCKER_RADIUS_PORT_INT"
      RADIUS_TEST_USER: "$SSO_DOCKER_OPENSSH_USER"
      RADIUS_TEST_HOST_SECRET: "$SSO_DOCKER_RADIUS_SECRET"
    command: /bin/bash -c 'echo "$$RADIUS_SERVER_ADDRESS:$$RADIUS_SERVER_PORT $$RADIUS_TEST_HOST_SECRET 1" > /etc/pam_radius_auth.conf; adduser --disabled-password --gecos "" --force-badname $$RADIUS_TEST_USER; service ssh restart; /sbin/my_init'

  nginx:
    container_name: $SSO_DOCKER_NGINX_NAME
    image: nginx
    volumes:
     - ./nginx/nginx.conf:/tmp/nginx.conf
    ports:
     - $SSO_DOCKER_NGINX_IDP_PORT:$SSO_DOCKER_NGINX_IDP_PORT_INT
     - $SSO_DOCKER_NGINX_RADIUS_PORT:$SSO_DOCKER_NGINX_RADIUS_PORT_INT/udp
    environment:
     SSO_DOCKER_IDP_PORT_INT: $SSO_DOCKER_IDP_PORT_INT
     SSO_DOCKER_NGINX_IDP_PORT_INT: $SSO_DOCKER_NGINX_IDP_PORT_INT
     SSO_DOCKER_RADIUS_PORT_INT: $SSO_DOCKER_RADIUS_PORT_INT
     SSO_DOCKER_NGINX_RADIUS_PORT_INT: $SSO_DOCKER_NGINX_RADIUS_PORT_INT
    command: /bin/sh -c "envsubst < /tmp/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
    depends_on:
      - sso

networks:
  radius:
    ipam:
      config:
      - subnet: 172.16.0.0/24
        gateway: 172.16.0.1
