#!/bin/bash

dir="$(dirname ${BASH_SOURCE[0]})"
. $dir/secrets.sh

# environment config
export COMPOSE_PROJECT_NAME=${SSO_DOCKER_NAME}
PREFIX=${SSO_DOCKER_NAME}_
export SSO_DOCKER_SSO_NAME=${PREFIX}sso
export SSO_DOCKER_CONSUL_NAME=${PREFIX}consul
export SSO_DOCKER_STATSD_NAME=${PREFIX}statsd
export SSO_DOCKER_REDIS_NAME=${PREFIX}redis
export SSO_DOCKER_LDAP_NAME=${PREFIX}ldap
export SSO_DOCKER_LDAPGUI_NAME=${PREFIX}ldapgui
export SSO_DOCKER_SYSLOG_NAME=${PREFIX}sylog
export SSO_DOCKER_SP_NAME=${PREFIX}sp

export SSO_DOCKER_CONSUL_PORT=${SSO_DOCKER_CONSUL_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 1)}
export SSO_DOCKER_STATSD_PORT=${SSO_DOCKER_STATSD_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 2)}
export SSO_DOCKER_REDIS_PORT=${SSO_DOCKER_REDIS_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 3)}
export SSO_DOCKER_LDAP_PORT=${SSO_DOCKER_LDAP_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 4)}
export SSO_DOCKER_LDAPGUI_PORT=${SSO_DOCKER_LDAPGUI_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 5)}

# srv-idp config
export SSO_DOCKER_IDP_BACKEND=${SSO_DOCKER_IDP_BACKEND:-$SSO_DOCKER_IDP_BACKEND_DEFAULT}
export SSO_DOCKER_IDP_CLIENTID=${SSO_DOCKER_IDP_CLIENTID:-$SSO_DOCKER_IDP_CLIENTID_DEFAULT}
export SSO_DOCKER_IDP_CLIENTSECRET=${SSO_DOCKER_IDP_CLIENTSECRET:-$SSO_DOCKER_IDP_CLIENTSECRET_DEFAULT}
export SSO_DOCKER_IDP_KEY=${SSO_DOCKER_IDP_KEY:-$SSO_DOCKER_IDP_KEY_DEFAULT}
export SSO_DOCKER_IDP_CERT=${SSO_DOCKER_IDP_CERT:-$SSO_DOCKER_IDP_CERT_DEFAULT}
export SSO_DOCKER_SP_KEY=${SSO_DOCKER_SP_KEY:-$SSO_DOCKER_SP_KEY_DEFAULT}
export SSO_DOCKER_SP_CERT=${SSO_DOCKER_SP_CERT:-$SSO_DOCKER_SP_CERT_DEFAULT}

export SSO_DOCKER_IDP_PORT=${SSO_DOCKER_IDP_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 0)}
export SSO_DOCKER_IDP_PORT_INT=${SSO_DOCKER_IDP_PORT_INT:-$(expr $SSO_DOCKER_PORT_BASE + 0)}
export SSO_DOCKER_SP_PORT=${SSO_DOCKER_SP_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 80)}

# srv-radius config
export SSO_DOCKER_RADIUS_BACKEND=${SSO_DOCKER_RADIUS_BACKEND:-$SSO_DOCKER_RADIUS_BACKEND_DEFAULT}
export SSO_DOCKER_RADIUS_CLIENTID=${SSO_DOCKER_RADIUS_CLIENTID:-$SSO_DOCKER_RADIUS_CLIENTID_DEFAULT}
export SSO_DOCKER_RADIUS_CLIENTSECRET=${SSO_DOCKER_RADIUS_CLIENTSECRET:-$SSO_DOCKER_RADIUS_CLIENTSECRET_DEFAULT}
export SSO_DOCKER_RADIUS_SECRET=${SSO_DOCKER_RADIUS_SECRET:-$SSO_DOCKER_RADIUS_SECRET_DEFAULT}

export SSO_DOCKER_RADIUS_PORT=${SSO_DOCKER_RADIUS_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 12)}
export SSO_DOCKER_RADIUS_PORT_INT=${SSO_DOCKER_RADIUS_PORT_INT:-1812}

# nginx config
export SSO_DOCKER_NGINX_IDP_PORT=${SSO_DOCKER_NGINX_IDP_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 6)}
export SSO_DOCKER_NGINX_IDP_PORT_INT=${SSO_DOCKER_NGINX_IDP_PORT_INT:-8000}
export SSO_DOCKER_NGINX_RADIUS_PORT=${SSO_DOCKER_NGINX_RADIUS_PORT:-$(expr $SSO_DOCKER_PORT_BASE + 7)}
export SSO_DOCKER_NGINX_RADIUS_PORT_INT=${SSO_DOCKER_NGINX_RADIUS_PORT_INT:-1812}
